version: "3.3"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
  postgres:
    image: postgres
    restart: always
    ports:
      - "27017:27017"
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ../../config/pginit.sql:/docker-entrypoint-initdb.d/init.sql
